name: db4hls-env
channels:
  - conda-forge
dependencies:
  - python=3.10.10
  - jupyterlab
  - jupyterlab-git
  - jsonschema-with-format-nongpl
  - pydot
  - graphviz
  - scikit-learn
  - tensorflow-cpu==2.11.1
  - tensorflow-datasets==4.8.3
  - webcolors
  - widgetsnbextension==3.6.0
  - pip==23.0.1
  - pytest
  - pytest-xdist
  - pytest-timeout
  - mysql
  - mysql-connector-python
  - pip:
      - hls4ml[profiling]==0.7.1
      - qkeras==0.9.0
      - conifer==0.2b0

